language: python
python:
- '2.7'
- '3.4'
- '3.5'
install:
- make get_miniconda
- export PATH=~/miniconda3/bin:$PATH
- conda update --yes conda
- make PYTHON_VERSION=$TRAVIS_PYTHON_VERSION install
- source activate anchor_py$TRAVIS_PYTHON_VERSION
before_script:
- git config --global user.email "olga.botvinnik@gmail.com"
- git config --global user.name "YeoLab"
- git config --global push.default simple
- export REPO_URL_GITHUB="https://$GH_TOKEN@github.com/$GH_REPO.git"
- export LANGUAGE=en_US.UTF-8
- export LANG=en_US.UTF-8
- export LC_ALL=en_US.UTF-8
- locale-gen en_US.UTF-8
- sudo dpkg-reconfigure locales
script:
- python -c "import anchor.tests"
- make coverage
- make lint
after_script:
- coveralls
deploy:
  provider: pypi
  user: obot
  password:
    secure: KLIIx6HQkgj3wkhLrcX06Ry9jztDl/mz5SV5xo1ZMmqRkNbME3UxVIF1SwlCLhdZvycVh6MvLBLn/8Uq8xGGxtFqBYGf3y1+Coalmmvv4X/fGUby0F8PkmegULwh6h65tqt5KtGIh9M0eknUYnx/Ib/r3ontd1yCrvul14LGyAcKOR9oP6nmrLOwIqMPXeD5s5zlrGvEKnTulxowOgKOGavnyxaFfBqmdRlGokbhXxUGGMmW3PNRx2jlSFTPozZwzp2mfCkKg/7hslwIYln4ovkTNXiFIiOMm4WRH9/Nzae3nSxTcMw7SB53lrgcL3HoA2sBS/sjh623VdWbuzUX9FQw3We9lb2AfJglsZgkW4xQ1wfKS9WwrgTwHN1Q7490//J4xk39SnTvm8sdNQYIKviNJLhmqPTEFJoxRZnbtmuLMrc5qi14663RLYhL/veTqHGi3J3iNwlK1tZax15CayXUeasuRjHlUcBvOnfpK6YYSuNvlFUGmzFNkAYPaX/BJ/J9il39LNTByregWzJThuct+hl2nG2V0VBFOSlzJgIVphQchcl5JMTF8dboR3BuuvxTMbb7LyU1mwQBO85jaT7ikJqZpG9o+cG2uJ5KYE4gt+LWaMReHVN9xWaWA+HsJginyP5WrnjSnivIetyw0f/oR5C1sCaVmb8DY80Ap0Q=
  on:
    tags: true
    repo: YeoLab/anchor
